### PR TITLE
Improve handling of AWS regions other than us-east-1

### PR DESCRIPTION
**Pull request by adamrothman**
These changes are required in order to use this tool in regions outside of the standard AWS partition (e.g. aws-us-gov or aws-cn):

* Use the AWS SDK to infer the correct S3 hostname given the configured region
* Set the configured region on the base AWS session

### CODE REVIEW

**Comment by adamrothman** [comment]
👋 Hi @adamvduke, it's me again. We've tested this in GovCloud and it appears to do the right thing. Eager to hear what you think.

**Comment by adamrothman** [comment]
It looks like that CI failure is because the Travis job uses Go 1.11.13, which is too old to understand the `%w` formatting directive for `fmt.Errorf`.

**Comment by adamrothman** [comment]
@adamvduke any chance you might be able to look at this soon?

**Review by adamvduke — APPROVED** [review]
Hi @adamrothman,

My apologies for taking so long to look at this. LGTM. I created a separate PR to bump the travis versions to min of 1.13, and I'll merge this when I get a ➕  on that.

**Pull request merged**
